/*
 * HCS API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

import "github.com/Microsoft/go-winio/pkg/guid"

type CimMount struct {
	ImagePath      string `json:"ImagePath,omitempty"`
	FileSystemName string `json:"FileSystemName,omitempty"`
	VolumeGuid     string `json:"VolumeGuid,omitempty"`
	MountFlags     uint32 `json:"MountFlags,omitempty"`
}

type BlockCIMMount struct {
	BlockLUNs  []uint32  `json:"BlockLUNs,omitempty"`
	CimNames   []string  `json:"CimNames,omitempty"`
	VolumeGuid guid.GUID `json:"VolumeGuid,omitempty"`
	MountFlags uint32    `json:"MountFlags,omitempty"`
}
