/*
 * HCS API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

// VM specific synthetic processor feature requirements
type EnlightenmentSet struct {
	// Synthetic processor features
	SyntheticProcessorFeatures []string `json:"SyntheticProcessorFeatures,omitempty"`
	// Processor feature set mode
	ProcessorFeatureSetMode string `json:"ProcessorFeatureSetMode,omitempty"`
}
